# Generated by Django 5.0.6 on 2026-07-28 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaBotanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Família Botânica',
                'verbose_name_plural': 'Famílias Botânicas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(help_text='Nome mais comum na região. Ex: Erva-cidreira', max_length=255)),
                ('outros_nomes', models.CharField(blank=True, help_text='Nomes regionais separados por vírgula', max_length=500)),
                ('nome_cientifico', models.CharField(help_text='Binômio científico. Ex: Melissa officinalis', max_length=255, unique=True)),
                ('descricao', models.TextField(help_text='Descrição morfológica e características gerais')),
                ('parte_utilizada', models.CharField(help_text='Ex: folhas, raízes, casca do caule', max_length=255)),
                ('usos_terapeuticos', models.TextField(help_text='Indicações terapêuticas com base em evidências')),
                ('modo_preparo', models.TextField(blank=True, help_text='Chá, tintura, cataplasma, etc. Com dosagem orientativa')),
                ('contraindicacoes', models.TextField(blank=True, help_text='Grupos de risco e situações de contraindicação')),
                ('interacoes_medicamentosas', models.TextField(blank=True, help_text='Interações com fármacos conhecidas')),
                ('nivel_toxicidade', models.CharField(choices=[('SEGURA', 'Segura para uso geral'), ('ATENCAO', 'Requer atenção (gestantes, crianças)'), ('RESTRITA', 'Uso restrito — apenas com orientação'), ('CONTRAINDICADA', 'Contraindicada para uso popular')], default='ATENCAO', max_length=20)),
                ('regiao_ocorrencia', models.CharField(blank=True, max_length=255)),
                ('origem', models.CharField(blank=True, help_text='Ex: Nativa da Mata Atlântica, Exótica da Ásia', max_length=255)),
                ('referencias_bibliograficas', models.TextField(blank=True, help_text='Artigos, farmacopeias, RDC Anvisa de referência')),
                ('registro_anvisa', models.CharField(blank=True, help_text='Número de registro ou instrumento normativo da Anvisa', max_length=100)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='plantas/fotos/')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_REVISAO', 'Em Revisão'), ('PUBLICADO', 'Publicado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=15)),
                ('data_curadoria', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curado_por', models.ForeignKey(blank=True, help_text='Especialista responsável pela validação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantas_curadas', to=settings.AUTH_USER_MODEL)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantas', to='botanica.familiabotanica')),
            ],
            options={
                'verbose_name': 'Planta Medicinal',
                'verbose_name_plural': 'Plantas Medicinais',
                'ordering': ['nome_popular'],
            },
        ),
    ]
