# Generated by Django 5.0.6 on 2026-07-28 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botanica', '0001_initial'),
        ('hortos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidade', models.CharField(choices=[('ABUNDANTE', 'Abundante'), ('DISPONIVEL', 'Disponível'), ('ESCASSA', 'Escassa'), ('INDISPONIVEL', 'Indisponível (fora de época)')], default='DISPONIVEL', max_length=15)),
                ('quantidade_estimada', models.PositiveIntegerField(blank=True, help_text='Número estimado de espécimes ou mudas disponíveis', null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('horto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='hortos.horto')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='botanica.planta')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['horto', 'planta'],
                'unique_together': {('horto', 'planta')},
            },
        ),
    ]
