# Generated by Django 6.0 on 2026-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPlantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_cientifico', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('parte_utilizada', models.CharField(blank=True, max_length=255)),
                ('usos', models.TextField(blank=True)),
                ('regiao', models.CharField(max_length=255)),
                ('origem', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
