# Generated by Django 5.0.6 on 2026-07-28 06:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(help_text='Ex: Instituto Federal, Unidade Básica de Saúde, ONG', max_length=100)),
                ('site', models.URLField(blank=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Horto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('municipio', models.CharField(default='Jaboatão dos Guararapes', max_length=100)),
                ('uf', models.CharField(default='PE', max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Longitude, Latitude. Ex: POINT(-35.012 -8.167)', srid=4326)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Em Manutenção')], default='ATIVO', max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hortos/fotos/')),
                ('horario_funcionamento', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hortos_gerenciados', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hortos', to='hortos.instituicao')),
            ],
            options={
                'verbose_name': 'Horto Medicinal',
                'verbose_name_plural': 'Hortos Medicinais',
                'ordering': ['nome'],
            },
        ),
    ]
