# Generated by Django 5.0.6 on 2026-07-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hortos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'ordering': ['nome'], 'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
    ]
